// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Config struct {
	ID           int64
	ClientSecret string
	ClientID     string
	RedirectUri  string
	Authorized   bool
	AccessToken  sql.NullString
	RefreshToken sql.NullString
	ExpiresAt    sql.NullString
}
